baseURL = "http://localhost:1313/"
googleAnalytics = ""

[params]
  rankingsURL = "https://arcos-angels-strava-client.herokuapp.com/json"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0