baseURL = "http://localhost:1313/"
googleAnalytics = ""

[params]
  rankingMembersRunURL = "http://localhost:8080/api/members/run"
  rankingMembersRideURL = "http://localhost:8080/api/members/ride"
  rankingFansRunURL = "http://localhost:8080/api/fans/run"
  rankingFansRideURL = "http://localhost:8080/api/fans/ride"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0