baseURL = "http://localhost:1313/"
googleAnalytics = ""

[params]
  rankingMembersURL = "http://localhost:8080/api/members"
  rankingFansURL = "http://localhost:8080/api/fans"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0