baseURL = "https://arcos-angels.nl/"
googleAnalytics = "UA-160866422-1"

[params]
  rankingsURL = "https://arcos-angels-strava-client.herokuapp.com/json"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0