baseURL = "https://arcos-angels.nl/"
googleAnalytics = "UA-160866422-1"

[params]
  rankingMembersURL = "https://arcos-angels-strava-client.herokuapp.com/api/members"
  rankingFansURL = "https://arcos-angels-strava-client.herokuapp.com/api/fans"

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = 0